name: Code-Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest pytest-cov selenium playwright
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    

    - name: Running pytest
      run: |
        pytest -v  --cov --cov-report=xml --cov-report=html
    
    - name: Mypy
      run: python -m mypy --non-interactive sql_query_parser
    
    - name: Flake8
      run: python -m flake8 sql_query_parser
    
    - name: Coverage test
      run: coverage run --source=sql_query_parser -m pytest
    
    - name: Coverage report
      run: coverage report --show-missing --skip-covered --skip-empty --omit="*test*,*exception*"


